spring:
  data:
    mongodb:
      uri: mongodb+srv://jingchen:jc4069369@clusterjc-zytbk.azure.mongodb.net/test?retryWrites=true&w=majority


behavior:
  collection:
    enable: true
    type: mongo
    appName: appName